import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Provider, StateDisplay } from '@/components';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <nav>
            <ul>
              <li>
                <Link href="/">Home</Link>
              </li>
              <li>
                <Link href="about">About</Link>
              </li>
              <li>
                <Link href="users">Users</Link>
              </li>
            </ul>
          </nav>
          <StateDisplay />
          {children}
        </Provider>
      </body>
    </html>
  );
}
